AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  heart-disease-deploy-sam

  Sample SAM Template for hear-disease-deploy-sam

Globals:
  Function:
    Timeout: 600

Resources:
  HeartMLPredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /predict
            Method: post
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./predict
      Dockerfile: Dockerfile

Outputs:
  HeartMLPredictApi:
    Description: "API Gateway endpoint URL for Prod stage for MLPredict function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  HeartMLPredictFunction:
    Description: "ML Prediction Lambda Function ARN"
    Value: !GetAtt HeartMLPredictFunction.Arn
  HeartMLPredictFunctionIamRole:
    Description: "Implicit IAM Role created for MLPredict function"
    Value: !GetAtt HeartMLPredictFunctionRole.Arn
