version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "diabeties-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-em49pbjvnsbp"
s3_prefix = "diabeties-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DiabetiesMLPredictFunction=855092383413.dkr.ecr.us-west-2.amazonaws.com/diabetesproject"]
